version: "3.8"

services:
  backend:
    build:
      context: ./backend
    expose:
      - "4567"
    volumes:
      - ./backend:/app
    networks:
      - app_net

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
     - type: bind
       source: ./frontend
       target: /app
       consistency: cached
     - type: volume
       source: node_modules
       target: /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    command: npm run dev  
    networks:
      - app_net

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app_net
    restart: always

volumes:
  node_modules:

networks:  
  app_net:
    driver: bridge
